// Vitest stand-in for `virtual:pwa-register/react` (generated by vite-plugin-pwa at build time).
export function useRegisterSW() {
  const noop = () => undefined;
  return {
    needRefresh: [false, noop] as const,
    offlineReady: [false, noop] as const,
    updateServiceWorker: async () => undefined,
  };
}
