import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useRegisterSW } from "virtual:pwa-register/react";

import { usePreferences } from "@/lib/preferences";

const UPDATE_TOAST_ID = "pwa-update";
// Check for a new deployment while a tab stays open (installed PWAs are rarely reloaded).
const UPDATE_CHECK_MS = 60 * 60 * 1000;

/**
 * Registers the Workbox service worker (`/sw.js`, generated by vite-plugin-pwa) and shows a
 * persistent "new version" toast when an update is waiting. "Muat ulang" activates the waiting
 * worker (skipWaiting) and reloads once it controls the page. Rendered only in the browser.
 */
function PwaUpdatePromptInner() {
  const { t } = usePreferences();
  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegisteredSW(_swUrl, registration) {
      if (!registration) return;
      window.setInterval(() => {
        if (registration.installing || !navigator.onLine) return;
        void registration.update().catch(() => undefined);
      }, UPDATE_CHECK_MS);
    },
  });

  useEffect(() => {
    if (!needRefresh) return;
    toast(t("pwaUpdateAvailable"), {
      id: UPDATE_TOAST_ID,
      duration: Number.POSITIVE_INFINITY,
      action: { label: t("pwaReload"), onClick: () => void updateServiceWorker(true) },
    });
  }, [needRefresh, t, updateServiceWorker]);

  return null;
}

export function PwaUpdatePrompt() {
  const [mounted, setMounted] = useState(false);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- service workers only exist in the browser; skip SSR.
  useEffect(() => setMounted(true), []);
  if (!mounted || !("serviceWorker" in navigator)) return null;
  return <PwaUpdatePromptInner />;
}
