/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCanvasRouteImport } from './routes/_authenticated/canvas'
import { Route as AuthenticatedGraphRouteImport } from './routes/_authenticated/graph'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes.index'
import { Route as AuthenticatedNotesNoteIdRouteImport } from './routes/_authenticated/notes.$noteId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'
import { Route as ApiPublicN8nBackupRouteImport } from './routes/api/public/n8n/backup'
import { Route as ApiPublicN8nBotRouteImport } from './routes/api/public/n8n/bot'
import { Route as ApiPublicN8nCaptureRouteImport } from './routes/api/public/n8n/capture'
import { Route as ApiPublicN8nDigestRouteImport } from './routes/api/public/n8n/digest'
import { Route as ApiPublicN8nEventsRouteImport } from './routes/api/public/n8n/events'
import { Route as ApiPublicN8nMaintenanceRouteImport } from './routes/api/public/n8n/maintenance'
import { Route as ApiPublicN8nRemindersRouteImport } from './routes/api/public/n8n/reminders'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicN8nCalendarSyncRouteImport } from './routes/api/public/n8n/calendar/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCanvasRoute = AuthenticatedCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraphRoute = AuthenticatedGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesNoteIdRoute =
  AuthenticatedNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nBackupRoute = ApiPublicN8nBackupRouteImport.update({
  id: '/api/public/n8n/backup',
  path: '/api/public/n8n/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nBotRoute = ApiPublicN8nBotRouteImport.update({
  id: '/api/public/n8n/bot',
  path: '/api/public/n8n/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nCaptureRoute = ApiPublicN8nCaptureRouteImport.update({
  id: '/api/public/n8n/capture',
  path: '/api/public/n8n/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nDigestRoute = ApiPublicN8nDigestRouteImport.update({
  id: '/api/public/n8n/digest',
  path: '/api/public/n8n/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nEventsRoute = ApiPublicN8nEventsRouteImport.update({
  id: '/api/public/n8n/events',
  path: '/api/public/n8n/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nMaintenanceRoute = ApiPublicN8nMaintenanceRouteImport.update({
  id: '/api/public/n8n/maintenance',
  path: '/api/public/n8n/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nRemindersRoute = ApiPublicN8nRemindersRouteImport.update({
  id: '/api/public/n8n/reminders',
  path: '/api/public/n8n/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nCalendarSyncRoute =
  ApiPublicN8nCalendarSyncRouteImport.update({
    id: '/api/public/n8n/calendar/sync',
    path: '/api/public/n8n/calendar/sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/canvas': typeof AuthenticatedCanvasRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/today': typeof AuthenticatedTodayRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/n8n/backup': typeof ApiPublicN8nBackupRoute
  '/api/public/n8n/bot': typeof ApiPublicN8nBotRoute
  '/api/public/n8n/capture': typeof ApiPublicN8nCaptureRoute
  '/api/public/n8n/digest': typeof ApiPublicN8nDigestRoute
  '/api/public/n8n/events': typeof ApiPublicN8nEventsRoute
  '/api/public/n8n/maintenance': typeof ApiPublicN8nMaintenanceRoute
  '/api/public/n8n/reminders': typeof ApiPublicN8nRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/n8n/calendar/sync': typeof ApiPublicN8nCalendarSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/canvas': typeof AuthenticatedCanvasRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/today': typeof AuthenticatedTodayRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/n8n/backup': typeof ApiPublicN8nBackupRoute
  '/api/public/n8n/bot': typeof ApiPublicN8nBotRoute
  '/api/public/n8n/capture': typeof ApiPublicN8nCaptureRoute
  '/api/public/n8n/digest': typeof ApiPublicN8nDigestRoute
  '/api/public/n8n/events': typeof ApiPublicN8nEventsRoute
  '/api/public/n8n/maintenance': typeof ApiPublicN8nMaintenanceRoute
  '/api/public/n8n/reminders': typeof ApiPublicN8nRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/n8n/calendar/sync': typeof ApiPublicN8nCalendarSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/canvas': typeof AuthenticatedCanvasRoute
  '/_authenticated/graph': typeof AuthenticatedGraphRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/n8n/backup': typeof ApiPublicN8nBackupRoute
  '/api/public/n8n/bot': typeof ApiPublicN8nBotRoute
  '/api/public/n8n/capture': typeof ApiPublicN8nCaptureRoute
  '/api/public/n8n/digest': typeof ApiPublicN8nDigestRoute
  '/api/public/n8n/events': typeof ApiPublicN8nEventsRoute
  '/api/public/n8n/maintenance': typeof ApiPublicN8nMaintenanceRoute
  '/api/public/n8n/reminders': typeof ApiPublicN8nRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/n8n/calendar/sync': typeof ApiPublicN8nCalendarSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/archive'
    | '/automations'
    | '/calendar'
    | '/canvas'
    | '/graph'
    | '/inbox'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/timeline'
    | '/today'
    | '/notes/$noteId'
    | '/projects/$projectId'
    | '/oauth/google-calendar/return'
    | '/notes/'
    | '/projects/'
    | '/api/public/hooks/reminders'
    | '/api/public/n8n/backup'
    | '/api/public/n8n/bot'
    | '/api/public/n8n/capture'
    | '/api/public/n8n/digest'
    | '/api/public/n8n/events'
    | '/api/public/n8n/maintenance'
    | '/api/public/n8n/reminders'
    | '/api/public/telegram/webhook'
    | '/api/public/n8n/calendar/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/archive'
    | '/automations'
    | '/calendar'
    | '/canvas'
    | '/graph'
    | '/inbox'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/timeline'
    | '/today'
    | '/notes/$noteId'
    | '/projects/$projectId'
    | '/oauth/google-calendar/return'
    | '/notes'
    | '/projects'
    | '/api/public/hooks/reminders'
    | '/api/public/n8n/backup'
    | '/api/public/n8n/bot'
    | '/api/public/n8n/capture'
    | '/api/public/n8n/digest'
    | '/api/public/n8n/events'
    | '/api/public/n8n/maintenance'
    | '/api/public/n8n/reminders'
    | '/api/public/telegram/webhook'
    | '/api/public/n8n/calendar/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/activity'
    | '/_authenticated/archive'
    | '/_authenticated/automations'
    | '/_authenticated/calendar'
    | '/_authenticated/canvas'
    | '/_authenticated/graph'
    | '/_authenticated/inbox'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/templates'
    | '/_authenticated/timeline'
    | '/_authenticated/today'
    | '/_authenticated/notes/$noteId'
    | '/_authenticated/projects/$projectId'
    | '/oauth/google-calendar/return'
    | '/_authenticated/notes/'
    | '/_authenticated/projects/'
    | '/api/public/hooks/reminders'
    | '/api/public/n8n/backup'
    | '/api/public/n8n/bot'
    | '/api/public/n8n/capture'
    | '/api/public/n8n/digest'
    | '/api/public/n8n/events'
    | '/api/public/n8n/maintenance'
    | '/api/public/n8n/reminders'
    | '/api/public/telegram/webhook'
    | '/api/public/n8n/calendar/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
  ApiPublicN8nBackupRoute: typeof ApiPublicN8nBackupRoute
  ApiPublicN8nBotRoute: typeof ApiPublicN8nBotRoute
  ApiPublicN8nCaptureRoute: typeof ApiPublicN8nCaptureRoute
  ApiPublicN8nDigestRoute: typeof ApiPublicN8nDigestRoute
  ApiPublicN8nEventsRoute: typeof ApiPublicN8nEventsRoute
  ApiPublicN8nMaintenanceRoute: typeof ApiPublicN8nMaintenanceRoute
  ApiPublicN8nRemindersRoute: typeof ApiPublicN8nRemindersRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicN8nCalendarSyncRoute: typeof ApiPublicN8nCalendarSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canvas': {
      id: '/_authenticated/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof AuthenticatedCanvasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graph': {
      id: '/_authenticated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedGraphRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/backup': {
      id: '/api/public/n8n/backup'
      path: '/api/public/n8n/backup'
      fullPath: '/api/public/n8n/backup'
      preLoaderRoute: typeof ApiPublicN8nBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/bot': {
      id: '/api/public/n8n/bot'
      path: '/api/public/n8n/bot'
      fullPath: '/api/public/n8n/bot'
      preLoaderRoute: typeof ApiPublicN8nBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/capture': {
      id: '/api/public/n8n/capture'
      path: '/api/public/n8n/capture'
      fullPath: '/api/public/n8n/capture'
      preLoaderRoute: typeof ApiPublicN8nCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/digest': {
      id: '/api/public/n8n/digest'
      path: '/api/public/n8n/digest'
      fullPath: '/api/public/n8n/digest'
      preLoaderRoute: typeof ApiPublicN8nDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/events': {
      id: '/api/public/n8n/events'
      path: '/api/public/n8n/events'
      fullPath: '/api/public/n8n/events'
      preLoaderRoute: typeof ApiPublicN8nEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/maintenance': {
      id: '/api/public/n8n/maintenance'
      path: '/api/public/n8n/maintenance'
      fullPath: '/api/public/n8n/maintenance'
      preLoaderRoute: typeof ApiPublicN8nMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/reminders': {
      id: '/api/public/n8n/reminders'
      path: '/api/public/n8n/reminders'
      fullPath: '/api/public/n8n/reminders'
      preLoaderRoute: typeof ApiPublicN8nRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/calendar/sync': {
      id: '/api/public/n8n/calendar/sync'
      path: '/api/public/n8n/calendar/sync'
      fullPath: '/api/public/n8n/calendar/sync'
      preLoaderRoute: typeof ApiPublicN8nCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCanvasRoute: typeof AuthenticatedCanvasRoute
  AuthenticatedGraphRoute: typeof AuthenticatedGraphRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCanvasRoute: AuthenticatedCanvasRoute,
  AuthenticatedGraphRoute: AuthenticatedGraphRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
  ApiPublicN8nBackupRoute: ApiPublicN8nBackupRoute,
  ApiPublicN8nBotRoute: ApiPublicN8nBotRoute,
  ApiPublicN8nCaptureRoute: ApiPublicN8nCaptureRoute,
  ApiPublicN8nDigestRoute: ApiPublicN8nDigestRoute,
  ApiPublicN8nEventsRoute: ApiPublicN8nEventsRoute,
  ApiPublicN8nMaintenanceRoute: ApiPublicN8nMaintenanceRoute,
  ApiPublicN8nRemindersRoute: ApiPublicN8nRemindersRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicN8nCalendarSyncRoute: ApiPublicN8nCalendarSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
